import React, { useState } from 'react';

const PasswordCheckerGeneratorArticle: React.FC = () => {
    const [isExpanded, setIsExpanded] = useState(false);

    return (
        <div className="bg-slate-800/50 p-6 rounded-lg">
            <div className={`relative transition-all duration-700 ease-in-out ${isExpanded ? 'max-h-[9999px]' : 'max-h-52 overflow-hidden'}`}>
                <article className="prose prose-invert max-w-none prose-p:text-gray-300 prose-headings:text-amber-400">
                    <h2>Password Entropy, Brute-Force Attacks, and Why Using the Web Crypto API is Essential for Secure Randomness</h2>
                    <p>
                        In an era where digital security is constantly under threat, the strength of our passwords is often the first and most critical line of defense. A weak password can be cracked in seconds by a determined attacker using a brute-force attack. Understanding what makes a password "strong" is not just about following a checklist; it's about a concept called entropy. Furthermore, when generating a password, the source of randomness used is paramount to its security. This guide explores the principles of password strength, the danger of brute-force attacks, and why modern tools must use cryptographically secure methods like the Web Crypto API.
                    </p>

                    <h3>The Four Pillars of Password Strength</h3>
                    <p>
                        A strong password is one that is difficult for both humans and computers to guess. Its strength is derived from its complexity and length, a combination often referred to as entropy. High entropy means there are a vast number of possible combinations, making it impractical for an attacker to guess. Password strength is typically evaluated based on four main criteria:
                    </p>
                    <ul className="list-disc pl-5">
                        <li><strong>Length:</strong> This is the single most important factor. Every additional character exponentially increases the number of possible combinations. A minimum of 12-16 characters is now recommended.</li>
                        <li><strong>Uppercase and Lowercase Letters:</strong> Including both cases (e.g., 'a' and 'A') doubles the character set, significantly increasing complexity.</li>
                        <li><strong>Numbers:</strong> Adding digits (0-9) further expands the pool of possible characters.</li>
                        <li><strong>Symbols:</strong> Special characters (e.g., <code>!@#$%^&amp;*</code>) add another layer of complexity that can thwart dictionary-based attacks.</li>
                    </ul>
                    <p>A strong password includes a mix of all four of these elements, making it resistant to common attack patterns.</p>

                    <h3>Understanding Brute-Force and Dictionary Attacks</h3>
                    <p>
                        A brute-force attack is an exhaustive trial-and-error method where an automated system attempts every possible combination of characters until the correct password is found. The time this takes is directly related to the password's entropy. A short, simple password (e.g., "123456" or "password") can be cracked almost instantly. A long, complex password could take modern computers centuries to crack. A dictionary attack is a more targeted version where the attacker uses a list of common words and phrases, often with common substitutions (like '@' for 'a'). This is why using common words, even with a few numbers, is still considered weak.
                    </p>
                    
                    <h3>True vs. Pseudo-Random: The Critical Role of the Web Crypto API</h3>
                    <p>
                        When a tool generates a "random" password, the quality of that randomness is crucial. For years, developers relied on <code>Math.random()</code> in JavaScript. However, <code>Math.random()</code> generates pseudo-random numbers. This means that while they appear random, they are generated by a deterministic algorithm. With enough information, the sequence of numbers can be predicted, which is a major security vulnerability for cryptographic purposes.
                    </p>
                    <p>
                        This is where the **Web Crypto API** comes in. Specifically, the <code>crypto.getRandomValues()</code> method provides access to the operating system's underlying source of cryptographically secure randomness. These numbers are generated from unpredictable sources (like hardware noise or mouse movements), making them truly non-deterministic and suitable for security-sensitive applications like generating passwords, encryption keys, or session tokens.
                    </p>
                    <p>
                        Any reputable password generator **must** use a cryptographically secure pseudo-random number generator (CSPRNG) like the one provided by the Web Crypto API. Relying on <code>Math.random()</code> creates a false sense of security and produces passwords that may be predictable to a sophisticated attacker. By understanding and implementing these core security principles, we can create passwords that provide a robust defense for our digital lives.
                    </p>
                
                    <div className="bg-gray-900/70 p-4 rounded-md my-4 border border-cyan-500/30">
                        <pre className="text-sm text-green-400 overflow-x-auto">
                            <code>{/* Example code will vary per article */}</code>
                        </pre>
                    </div>
                </article>
                {!isExpanded && (
                    <div className="absolute bottom-0 left-0 right-0 h-24 bg-gradient-to-t from-gray-800/50 to-transparent"></div>
                )}
            </div>
            <button 
                onClick={() => setIsExpanded(!isExpanded)} 
                className="text-amber-400 hover:text-cyan-300 font-semibold mt-4"
            >
                {isExpanded ? 'Show Less' : 'Read More...'}
            </button>
        </div>
    );
};

export default PasswordCheckerGeneratorArticle;