import React from 'react';

const SmallClaimsFormTemplateArticle: React.FC = () => {
    return (
        <article className="prose prose-invert max-w-none prose-p:text-gray-300 prose-headings:text-emerald-400">
            <h2>An Introduction to Small Claims Court (For Educational Purposes)</h2>
            <p>
                Small claims court is a special part of the court system designed to resolve civil disputes involving small amounts of money in a simplified, informal setting. It allows individuals and businesses to settle disagreements without the high cost and complexity of hiring an attorney. Common types of cases include contract disputes, property damage, and landlord/tenant issues.
            </p>

            <h3>The Small Claims Process</h3>
            <p>
                While the process varies by state and county, it generally involves these steps:
            </p>
            <ol className="list-decimal list-inside">
                <li><strong>Fill Out the Forms:</strong> You (the "plaintiff") must fill out the official court forms. This typically includes a "Plaintiff's Statement" or "Complaint" where you identify the person you are suing (the "defendant") and clearly explain the facts of your case and why they owe you money.</li>
                <li><strong>File the Claim:</strong> You file the completed forms with the court clerk and pay a filing fee.</li>
                <li><strong>Serve the Defendant:</strong> You must formally notify the defendant that you are suing them. This is called "service of process" and must be done according to your local court's rules.</li>
                <li><strong>Go to Court:</strong> Both parties appear before a judge or commissioner who will hear both sides of the story and make a ruling.</li>
            </ol>

            <h3>CRITICAL LEGAL DISCLAIMER</h3>
            <p>
                The information provided here and the template generated by this tool are for **educational and informational purposes ONLY**. They are absolutely **NOT** a substitute for legal advice or the official court forms. Court rules are strict and vary by location. Using the wrong form or failing to follow the correct procedure will result in your case being dismissed. You **MUST** contact your local county courthouse to obtain the official, required forms and instructions for filing a small claims case.
            </p>
        </article>
    );
};

export default SmallClaimsFormTemplateArticle;